import { prepareFrame } from './frame-preparation';
const LIMIT=256*1024*1024;
export function installPreviewCache(PM:any) {
  let generation=0;const frames=new Map<number,ImageBitmap>();let signature='',preparing=false,active=false,canvas:HTMLCanvasElement|null=null,raf=0;
  const key=()=>[PM.proj.id,PM.animVersion?.()||0,PM.GL.canvas?.width||0,PM.GL.canvas?.height||0,PM.previewFps||PM.proj.fps,PM.proj.work?.join(',')].join('|');
  const clear=()=>{generation++;active=false;PM.Audio?.pause();cancelAnimationFrame(raf);canvas?.remove();canvas=null;for(const f of frames.values())f.close();frames.clear();PM.bus.emit('preview');};
  const stop=()=>{active=false;cancelAnimationFrame(raf);canvas?.remove();canvas=null;PM.Audio.pause();PM.bus.emit('preview');PM.invalidate();};
  const play=()=>{if(!frames.size)return;if(signature!==key()){clear();return;}PM.pause();active=true;const fps=PM.previewFps||PM.proj.fps,start=PM.proj.work?.[0]||0,first=performance.now();canvas=document.createElement('canvas');canvas.width=PM.GL.canvas.width;canvas.height=PM.GL.canvas.height;canvas.style.cssText='position:absolute;inset:0;width:100%;height:100%;pointer-events:none;z-index:2';PM.GL.canvas.parentElement?.appendChild(canvas);const ctx=canvas.getContext('2d')!;PM.Audio.start(start);let lastCycle=0,lastTick=first;
    const tick=(now:number)=>{if(!active)return;if(signature!==key()){clear();return;}const elapsed=Math.floor((now-first)*fps/1000),i=elapsed%frames.size;const cycle=Math.floor(elapsed/frames.size);if(cycle!==lastCycle||now-lastTick>250)PM.Audio.seek(start+i/fps);lastCycle=cycle;lastTick=now;ctx.drawImage(frames.get(i)!,0,0);PM.time=start+i/fps;PM.bus.emit('time',PM.time);PM.bus.emit('overlay');PM.invalidate('timeline');raf=requestAnimationFrame(tick);};raf=requestAnimationFrame(tick);PM.bus.emit('preview');};
  PM.Preview={clear,stop,play,get active(){return active;},get preparing(){return preparing;},get count(){return frames.size;},cancel:()=>{generation++;},async cache(){if(preparing)return;clear();preparing=true;PM.pause();const own=generation,old=PM.time,w=PM.GL.canvas.width,h=PM.GL.canvas.height,fps=PM.previewFps||PM.proj.fps,[start,end]=PM.proj.work||[0,PM.proj.dur],count=Math.max(1,Math.ceil((end-start)*fps));signature=key();
    try{if(count*w*h*4>LIMIT)throw new Error('Preview exceeds 256 MB. Shorten the work area or lower preview resolution.');for(let i=0;i<count;i++){if(own!==generation||signature!==key())break;await prepareFrame(PM,start+i/fps);PM.GL.render(start+i/fps,{mblur:true,mbSamples:6});const bitmap=await createImageBitmap(PM.GL.canvas);if(own!==generation){bitmap.close();break;}frames.set(i,bitmap);PM.bus.emit('preview');await new Promise(r=>setTimeout(r,0));}if(frames.size===count&&own===generation)play();}
    catch(e){clear();PM.toast((e as Error).message,6000);}finally{preparing=false;if(!active)PM.time=old;PM.bus.emit('preview');PM.invalidate();}
  }};
  PM.bus.on('project',clear);PM.bus.on('layers',()=>{if(signature!==key())clear();});PM.bus.on('quality',clear);
}
