import { test, expect } from './helpers/app';
test.beforeEach(async ({ session }) => { await session.openEditor(); });
test('editable 2.5D layers render perspective, depth, keyframes and survive Undo and save', async ({ session }) => {
    const { page } = session;
    await page.waitForFunction(() => Boolean((window as any).PM?.GL?.gl));
    const result = await page.evaluate(() => {
        const PM = (window as any).PM, proj = PM.mkProject({ name: '2.5D review', w: 640, h: 360, dur: 5, bg: '#101018' });
        const a = PM.mkLayer('shape', { name: 'Coral card', d: { w: 240, h: 180, color: '#FF6040' }, p: { 'position.x': 320, 'position.y': 180 } }, proj);
        const b = PM.mkLayer('shape', { name: 'Blue card', d: { w: 240, h: 180, color: '#4060FF' }, p: { 'position.x': 360, 'position.y': 180 } }, proj);
        proj.layers = [a, b];
        PM.replaceProject(proj);
        PM.setTime(0, { force: true });
        const pixels = () => { const cv = PM.renderFrameTo(0, 640, 360); return Array.from(cv.getContext('2d').getImageData(0, 0, 640, 360).data) as number[]; };
        const before = pixels();
        const enabled = PM.Edit.apply([a, b].map(l => ({ type: 'set_layer', target: l.id, patch: { threeD: true } })), { label: 'Enable 3D', origin: 'inspector' });
        const neutral = pixels();
        const undo = PM.hist.undo(), undone = PM.L(a.id).threeD;
        PM.hist.redo();
        const edited = PM.Edit.apply([{ type: 'set_property', target: a.id, path: 'position.z', value: 200 }, { type: 'set_property', target: b.id, path: 'position.z', value: -80 }, { type: 'set_property', target: b.id, path: 'rotation.y', value: -35 }], { label: 'Place cards', origin: 'inspector' });
        const after = pixels(), i = (180 * 640 + 340) * 4, pick = PM.GL.pick(340, 180, 0)?.id;
        const animated = PM.Edit.apply([{ type: 'set_property', target: b.id, path: 'rotation.x', value: 0, time: 0, mode: 'keyframe' }, { type: 'set_property', target: b.id, path: 'rotation.x', value: 40, time: 2, mode: 'keyframe' }], { label: 'Animate tilt', origin: 'inspector' });
        PM.selectLayers(b.id);
        PM.invalidate();
        return { enabled, edited, animated, neutral: JSON.stringify(before) === JSON.stringify(neutral), changed: JSON.stringify(after) !== JSON.stringify(neutral), undo, undone: !!undone, picked: pick === b.id, center: after.slice(i, i + 3), saved: JSON.parse(PM.serialize()).proj.layers.map((l: any) => ({ threeD: l.threeD, z: l.p['position.z'].v, keys: l.p['rotation.x'].kf.length })), errors: [...PM.GL.errors.entries()] };
    });
    expect(result.enabled.ok).toBe(true);
    expect(result.edited.ok).toBe(true);
    expect(result.animated.ok).toBe(true);
    expect(result.neutral).toBe(true);
    expect(result.changed).toBe(true);
    expect(result.undo).toBe(true);
    expect(result.undone).toBe(false);
    expect(result.picked).toBe(true);
    expect(result.center[2]).toBeGreaterThan(result.center[0]);
    expect(result.saved).toEqual([{ threeD: true, z: 200, keys: 0 }, { threeD: true, z: -80, keys: 2 }]);
    expect(result.errors).toEqual([]);
    await expect(page.getByRole('radiogroup', { name: '3D layer', exact: true })).toBeVisible();
    const perspective = page.getByRole('spinbutton', { name: 'Perspective', exact: true });
    await expect(perspective).toBeVisible();
    await perspective.focus();
    await perspective.fill('10000');
    await perspective.press('Enter');
    expect(await page.evaluate(() => (window as any).PM.firstSel().p.perspective.v)).toBe(10000);
    await page.evaluate(() => { const PM = (window as any).PM; PM.replaceProject(PM.deserialize(PM.serialize())); });
    await expect(perspective).toHaveValue('10000mm');
    await perspective.focus();
    await perspective.fill('50');
    await perspective.press('Enter');
    await page.getByRole('radiogroup', { name: '3D layer', exact: true }).getByRole('radio', { name: 'Off', exact: true }).click();
    await expect(page.getByRole('spinbutton', { name: 'Position Z', exact: true })).toHaveCount(0);
    await page.getByRole('radiogroup', { name: '3D layer', exact: true }).getByRole('radio', { name: 'On', exact: true }).click();
    await expect(page.getByRole('spinbutton', { name: 'Position Z', exact: true })).toBeVisible();
    await page.screenshot({ path: '/tmp/powermove-25d-review.png' });
    const drag = await page.evaluate(() => { const PM = (window as any).PM, viewer = PM.Kernel.services.get('viewer'), l = PM.firstSel(), p = viewer.layerWorldPivot(l, 0), r = viewer.inner.getBoundingClientRect(); return { x: r.left + p.x * viewer.shown, y: r.top + p.y * viewer.shown, position: PM.ev(l, 'position.x', 0), zoom: viewer.shown }; });
    await page.mouse.move(drag.x, drag.y);
    await page.mouse.down();
    await page.mouse.move(drag.x + 60, drag.y + 20, { steps: 8 });
    await page.mouse.up();
    const moved = await page.evaluate(() => { const PM = (window as any).PM, viewer = PM.Kernel.services.get('viewer'), l = PM.firstSel(), p = viewer.layerWorldPivot(l, 0), r = viewer.inner.getBoundingClientRect(); return { x: r.left + p.x * viewer.shown, y: r.top + p.y * viewer.shown }; });
    expect(moved.x - drag.x).toBeCloseTo(60, 0);
    expect(moved.y - drag.y).toBeCloseTo(20, 0);
    await page.evaluate(() => { const PM = (window as any).PM; PM.hist.undo(); PM.replaceProject(PM.deserialize(PM.serialize())); });
    await expect(page.getByRole('spinbutton', { name: 'Position Z', exact: true })).toHaveValue('-80px');
    expect(session.diagnostics.pageErrors).toEqual([]);
});
