import type { PowermoveAgentToolSpec } from './spec';

const object = (properties: Record<string, unknown>, required: string[] = []) => ({ type: 'object', additionalProperties: false, properties, ...(required.length ? { required } : {}) });
export const EXTERNAL_MCP_INSTRUCTIONS = `Use list_projects, create_project or open_project before start_session. start_session pins the project and returns the same isolated workspace and API documentation used by the Powermove harness. Use the editing tools, render_frames and get_workspace_state to create and verify the video. publish_extensions validates and loads staged extensions. import_media reads files on the host. save_project writes an editable .pmv; export_video writes a finished MP4 or ProRes video with sound. Call finish_session with commit:true to keep edits; disconnecting cancels children and attempts to roll back unfinished composition edits. Async delegation and thread watches do not wake an external client: use mode:wait or task_status/thread_read. The host may be a hidden editor; the desktop app need not be open. Store and 3D capabilities depend on the host's configuration. Never assume a timed-out mutation failed; inspect before repeating it.`;

export const EXTERNAL_MCP_TOOLS: readonly PowermoveAgentToolSpec[] = [
  { name: 'list_projects', description: 'List saved projects and the current project in this Powermove host.', inputSchema: object({}) },
  { name: 'create_project', description: 'Create and open a new empty video project without a dialog. Finish any active MCP session first. Returns its ID and format.', inputSchema: object({ name: { type: 'string', minLength: 1, maxLength: 120 }, width: { type: 'integer', minimum: 2, maximum: 8192 }, height: { type: 'integer', minimum: 2, maximum: 8192 }, fps: { type: 'number', minimum: 1, maximum: 120 }, duration: { type: 'number', minimum: 0.1, maximum: 36000 } }, ['name']) },
  { name: 'open_project', description: 'Open a saved project by ID from list_projects. Finish any active MCP session first.', inputSchema: object({ projectId: { type: 'string', minLength: 1, maxLength: 120 } }, ['projectId']) },
  { name: 'start_session', description: 'Start a project or app tool session, pinned to the currently open project. Returns private staging/workspace paths, the API pack and harness instructions. Planning access only exposes inspection tools. Filesystem paths refer to this host. Only one session per connection is active.', inputSchema: object({ prompt: { type: 'string', minLength: 1, maxLength: 200000 }, access: { type: 'string', enum: ['project', 'editor'] }, context: { type: 'string', enum: ['project', 'app'] } }, ['prompt']) },
  { name: 'publish_extensions', description: 'Validate, compile, secret-scan and atomically promote declared staged extension changes, then reload them. Keep the session open to verify registration and render output. Failed validation leaves the stage available to repair. Publishing here installs locally; Store publishing uses store_publish.', inputSchema: object({ extensions: { type: 'array', maxItems: 100, items: object({ id: { type: 'string' }, action: { type: 'string', enum: ['created', 'updated', 'removed'] }, summary: { type: 'string' } }, ['id', 'action', 'summary']) } }, ['extensions']) },
  { name: 'import_media_to_timeline', description: 'Import a host-local video, audio, image or model file through Powermove\'s media importer. Requires project access. Returns asset/layer IDs; optional at places it in the timeline. Hidden hosts support this without any file picker.', inputSchema: object({ path: { type: 'string', minLength: 1 }, at: { type: 'number', minimum: 0 } }, ['path']) },
  { name: 'finish_session', description: 'Finish this session: commit keeps live edits in normal Undo history; false rolls back guarded edits. Pending subagents are cancelled and drained first. Locally published extensions and already exported files remain. A warning reports edits that could not be rolled back safely.', inputSchema: object({ commit: { type: 'boolean' } }, ['commit']) }
];
