import { test, expect } from 'bun:test';
import { createApp } from '../src/app';
import { desktopAuth } from '../src/db/schema';
import { eq } from 'drizzle-orm';
import { withData } from './db';
import { makeEnv } from './env';
import { seedSession } from './helpers';
const b64=(bytes:Uint8Array)=>btoa(String.fromCharCode(...bytes)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
async function setup(data:Parameters<typeof makeEnv>[0],env:CloudflareBindings,browserHeaders:Record<string,string>,expired=false){
 const verifier=b64(crypto.getRandomValues(new Uint8Array(32)));const bytes=Uint8Array.from(atob(verifier.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));const challenge=b64(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)));const state=crypto.randomUUID().replaceAll('-','');
 await data.db.insert(desktopAuth).values({state,challenge,expiresAt:new Date(Date.now()+(expired?-1000:600_000))});
 const app=createApp({data:()=>data});const done=await app.request(`/v1/auth/desktop/done?state=${state}`,{headers:browserHeaders},env);
 if(expired){expect(done.status).toBe(401);return {app,state,verifier,token:''};}
 expect(done.status).toBe(200);const html=await done.text();const match=html.match(/powermove:\/\/auth\?state=[^"<]+/);expect(match).not.toBeNull();const url=new URL(match![0].replaceAll('&amp;','&'));return {app,state,verifier,token:url.searchParams.get('token')!};
}
test('desktop exchange creates separate bearer session and consumes state',async()=>withData(async data=>{const env=makeEnv(data),app=createApp({data:()=>data});let line='';const old=console.log;console.log=(...args)=>{line=args.join(' ')};try{await app.request('/v1/auth/email/send',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:'desktop@example.com'})},env);}finally{console.log=old;}const otp=line.match(/: ([0-9]+)$/)?.[1];expect(otp).toBeDefined();const login=await app.request('/v1/auth/sign-in/email-otp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:'desktop@example.com',otp})},env);expect(login.status).toBe(200);const cookie=login.headers.get('set-cookie')?.split(';')[0];expect(cookie).toBeDefined();const browser=await login.json() as {user:{id:string};token:string};const flow=await setup(data,env,{Cookie:cookie!});const body={state:flow.state,verifier:flow.verifier,token:flow.token};const exchange=()=>flow.app.request('/v1/auth/desktop/exchange',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)},env);const first=await exchange();expect(first.status).toBe(200);const result=await first.json() as any;expect(result.token).not.toBe(browser.token);expect(new Date(result.expiresAt).getTime()).toBeGreaterThan(Date.now());const me=await flow.app.request('/v1/me',{headers:{Authorization:`Bearer ${result.token}`}},env);expect(me.status).toBe(200);expect((await me.json() as any).user.id).toBe(browser.user.id);expect((await exchange()).status).toBe(401);}));
test('wrong verifier consumes the desktop row',async()=>withData(async data=>{const env=makeEnv(data),browser=await seedSession(data,env),flow=await setup(data,env,{Authorization:`Bearer ${browser.token}`});const exchange=(verifier:string)=>flow.app.request('/v1/auth/desktop/exchange',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({state:flow.state,token:flow.token,verifier})},env);expect((await exchange(b64(new Uint8Array(32)))).status).toBe(401);expect((await exchange(flow.verifier)).status).toBe(401);}));
test('expired desktop row is rejected and consumed',async()=>withData(async data=>{const env=makeEnv(data),browser=await seedSession(data,env),flow=await setup(data,env,{Authorization:`Bearer ${browser.token}`},true);const res=await flow.app.request('/v1/auth/desktop/exchange',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({state:flow.state,token:'invalid',verifier:flow.verifier})},env);expect(res.status).toBe(401);const [row]=await data.db.select().from(desktopAuth).where(eq(desktopAuth.state,flow.state));expect(row.consumedAt).not.toBeNull();}));
