// Worker bindings. `CloudflareBindings` is generated by `wrangler types` from
// wrangler.jsonc, so adding an R2 bucket or a secret there flows into `c.env`.
export type Env = { Bindings: CloudflareBindings };
